import React from 'react';

const LegalPage = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white shadow-md rounded-lg overflow-hidden">
        
        {/* Header Section */}
        <div className="bg-green-600 px-6 py-8 sm:p-10">
          <h1 className="text-3xl font-extrabold text-white">
            AgriGuard Legal & Privacy
          </h1>
          <p className="mt-2 text-green-100 text-sm">
            Please read these terms carefully before using the AgriGuard System.
          </p>
        </div>

        {/* Content Section */}
        <div className="px-6 py-8 sm:p-10 text-gray-700 space-y-12">
          
          {/* --- EULA SECTION --- */}
          <section>
            <div className="border-b border-gray-200 pb-4 mb-6">
              <h2 className="text-2xl font-bold text-gray-900">
                End-User Licence Agreement (EULA)
              </h2>
              <p className="text-sm text-gray-500 mt-1">Last Updated: March 2026</p>
            </div>

            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  1. Nature of Predictions — Advisory Use Only
                </h3>
                <p className="leading-relaxed">
                  All crop yield predictions, health status assessments (Green/Yellow/Red), and farming advisories generated by the System are provided for informational and decision-support purposes only. They are not guarantees of actual crop performance. Predictions are based on historical data and satellite-derived environmental indices and may not account for all local conditions. You are solely responsible for any farming, financial, or operational decisions made in reliance on System outputs.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  2. Data Collection and Consent
                </h3>
                <p className="leading-relaxed">
                  By registering on the System, you consent to the collection of your mobile phone number and farm GPS coordinates for the purpose of delivering personalised crop monitoring and yield predictions. This data will not be used for any other purpose. You may withdraw consent and request deletion of your data at any time.
                </p>
              </div>
            </div>
          </section>

          {/* --- PRIVACY POLICY SECTION --- */}
          <section>
            <div className="border-b border-gray-200 pb-4 mb-6">
              <h2 className="text-2xl font-bold text-gray-900">
                Privacy Policy
              </h2>
              <p className="text-sm text-gray-500 mt-1">Last Updated: March 2026</p>
            </div>

            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  1. Third-Party Data Flows
                </h3>
                <p className="leading-relaxed">
                  To deliver satellite vegetation data and weather forecasts, your farm GPS coordinates are transmitted to Google Earth Engine and Open-Meteo. These transmissions occur each time an AI prediction is generated for your farm. These providers process the coordinates solely for the purpose of returning environmental data. No personal identifiers (such as your phone number or name) are ever transmitted to these external providers.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  2. Data Security and Anonymisation
                </h3>
                <p className="leading-relaxed">
                  All data transmitted between your device and the AgriGuard system is encrypted using HTTPS. Farm data stored in the database is held under an anonymised, randomly generated Farm ID; your phone number is intentionally segregated and not stored alongside your predictive farm data.
                </p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  3. Your Rights
                </h3>
                <p className="leading-relaxed">
                  In accordance with Rwanda's Law No. 058/2021 on the Protection of Personal Data and Privacy, you have the right to access the personal data held about you, to request correction of inaccurate data, to request deletion of your data, and to withdraw consent at any time without affecting your right to use the System up to that point.
                </p>
              </div>
            </div>
          </section>

        </div>
        
        {/* Footer / Actions */}
        <div className="bg-gray-50 px-6 py-4 border-t border-gray-200 sm:px-10 flex justify-end">
          <button 
            onClick={() => window.history.back()}
            className="text-sm font-medium text-green-600 hover:text-green-500 transition-colors"
          >
            &larr; Go Back
          </button>
        </div>

      </div>
    </div>
  );
};

export default LegalPage;